kind: Namespace 
apiVersion: v1
metadata:
  name: nginx


---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  namespace: nginx 
spec:
  replicas: 2
  selector:
    matchLabels:
        app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
         - name: nginx
           image: nginx:latest
           ports:
              - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  name: nginx-sersvice
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  